apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-cep
  description: API simples em FastAPI para consultar CEP via ViaCEP
  tags:
    - api
    - rest
    - python
    - fastapi
    - docker
    - backend
    - experimental
  annotations:
    github.com/project-slug: matheusgomide/api-cep
  links:
    - url: https://github.com/matheusgomide/api-cep
      title: Repositório (GitHub)
      icon: github
    - url: http://localhost:3000/api-docs
      title: API Docs (Backstage)
      icon: docs
    - url: http://localhost:8000/docs
      title: Swagger UI (FastAPI)
      icon: docs
    - url: https://viacep.com.br
      title: ViaCEP ( Serviço Externo)
      icon: web
      type: external-dependency
spec:
  type: service
  lifecycle: production
  owner: group:default/team-cep
  providesApis:
    - api-cep
  dependsOn:
    - resource:default/viacep-api
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: viacep-api
  description: API externaViaCEP áraconsulta deCEPs brasileiros
  tags:
    - external
    - api
    - third-party
  links:
    - url: https://viacep.com.br
    - title: ViaCEP WebSite
    - icon: web
    - url: https://viacep.com.br/ws01310100/json/
    - title: Exemplo de Consulta
    - icon: docs   
spec:
  type: external-api
  owner: group:default/team-cep
  dependencyOf:
    - component:default/api-cep